<?xml version="1.0"?>
<package format="2">
  <name>kimm_phri_panda_husky</name>
  <version>0.0.1</version>
  <description>CM 기반 차동구동 모바일 매니퓰레이터 협업 운반 시뮬레이션</description>

  <maintainer email="jspark2090@kimm.re.kr">Jinseong Park</maintainer>

  <license>MIT</license>

  <buildtool_depend>catkin</buildtool_depend>
  <build_depend>eigen</build_depend>

  <depend>geometry_msgs</depend>
  <depend>kimm_hqp_controller</depend>
  <depend>mujoco_ros_msgs</depend>
  <depend>roscpp</depend>
  <depend>sensor_msgs</depend>
  <depend>std_msgs</depend>
  <depend>yaml-cpp</depend>

</package>
